# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transactionConsumer.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19transactionConsumer.proto\x12\x07message\"8\n\x0f\x41skForSubscribe\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x14\n\x0c\x63onsumerName\x18\x02 \x01(\t\"$\n\x15\x41skForSubscribeReplay\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t\"\x1a\n\x0b\x41skForQuees\x12\x0b\n\x03\x61sk\x18\x01 \x01(\t\"&\n\x11\x41skForQueesReplay\x12\x11\n\tlistQuees\x18\x01 \x03(\t\"6\n\rAskForMessage\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x14\n\x0c\x63onsumerName\x18\x02 \x01(\t\"\"\n\x13\x41skForMessageReplay\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t2\xde\x01\n\x08\x43onsumer\x12G\n\tSubscribe\x12\x18.message.AskForSubscribe\x1a\x1e.message.AskForSubscribeReplay\"\x00\x12?\n\tListQuees\x12\x14.message.AskForQuees\x1a\x1a.message.AskForQueesReplay\"\x00\x12H\n\x0e\x43onsumeMessage\x12\x16.message.AskForMessage\x1a\x1c.message.AskForMessageReplay\"\x00\x42+\n\x10\x63om.CSTB.messageB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transactionConsumer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.CSTB.messageB\017HelloWorldProtoP\001\242\002\003HLW'
  _globals['_ASKFORSUBSCRIBE']._serialized_start=38
  _globals['_ASKFORSUBSCRIBE']._serialized_end=94
  _globals['_ASKFORSUBSCRIBEREPLAY']._serialized_start=96
  _globals['_ASKFORSUBSCRIBEREPLAY']._serialized_end=132
  _globals['_ASKFORQUEES']._serialized_start=134
  _globals['_ASKFORQUEES']._serialized_end=160
  _globals['_ASKFORQUEESREPLAY']._serialized_start=162
  _globals['_ASKFORQUEESREPLAY']._serialized_end=200
  _globals['_ASKFORMESSAGE']._serialized_start=202
  _globals['_ASKFORMESSAGE']._serialized_end=256
  _globals['_ASKFORMESSAGEREPLAY']._serialized_start=258
  _globals['_ASKFORMESSAGEREPLAY']._serialized_end=292
  _globals['_CONSUMER']._serialized_start=295
  _globals['_CONSUMER']._serialized_end=517
# @@protoc_insertion_point(module_scope)
