# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import transactionConsumer_pb2 as transactionConsumer__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in transactionConsumer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ConsumerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_unary(
                '/message.Consumer/Subscribe',
                request_serializer=transactionConsumer__pb2.AskForSubscribe.SerializeToString,
                response_deserializer=transactionConsumer__pb2.AskForSubscribeReplay.FromString,
                _registered_method=True)
        self.ListQuees = channel.unary_unary(
                '/message.Consumer/ListQuees',
                request_serializer=transactionConsumer__pb2.AskForQuees.SerializeToString,
                response_deserializer=transactionConsumer__pb2.AskForQueesReplay.FromString,
                _registered_method=True)
        self.ConsumeMessage = channel.unary_unary(
                '/message.Consumer/ConsumeMessage',
                request_serializer=transactionConsumer__pb2.AskForMessage.SerializeToString,
                response_deserializer=transactionConsumer__pb2.AskForMessageReplay.FromString,
                _registered_method=True)


class ConsumerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListQuees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsumeMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsumerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=transactionConsumer__pb2.AskForSubscribe.FromString,
                    response_serializer=transactionConsumer__pb2.AskForSubscribeReplay.SerializeToString,
            ),
            'ListQuees': grpc.unary_unary_rpc_method_handler(
                    servicer.ListQuees,
                    request_deserializer=transactionConsumer__pb2.AskForQuees.FromString,
                    response_serializer=transactionConsumer__pb2.AskForQueesReplay.SerializeToString,
            ),
            'ConsumeMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsumeMessage,
                    request_deserializer=transactionConsumer__pb2.AskForMessage.FromString,
                    response_serializer=transactionConsumer__pb2.AskForMessageReplay.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.Consumer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('message.Consumer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Consumer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.Consumer/Subscribe',
            transactionConsumer__pb2.AskForSubscribe.SerializeToString,
            transactionConsumer__pb2.AskForSubscribeReplay.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListQuees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.Consumer/ListQuees',
            transactionConsumer__pb2.AskForQuees.SerializeToString,
            transactionConsumer__pb2.AskForQueesReplay.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsumeMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.Consumer/ConsumeMessage',
            transactionConsumer__pb2.AskForMessage.SerializeToString,
            transactionConsumer__pb2.AskForMessageReplay.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
